apiVersion: v1
kind: ConfigMap
metadata:
  name: element-config
data:
  config.json: |
    {
        "default_server_config": {
            "m.homeserver": {
                "base_url": "https://{{ .Values.homeserver_url }}",
                "server_name": "{{ .Values.homeserver_url }}"
            },
            "m.identity_server": {
                "base_url": "https://vector.im"
            }
        },
        "disable_custom_urls": true,
        "disable_guests": true,
        "disable_login_language_selector": false,
        "disable_3pid_login": true,
        "brand": "Gluo",
        "integrations_ui_url": "https://scalar.vector.im/",
        "integrations_rest_url": "https://scalar.vector.im/api",
        "integrations_widgets_urls": [
            "https://scalar.vector.im/_matrix/integrations/v1",
            "https://scalar.vector.im/api",
            "https://scalar-staging.vector.im/_matrix/integrations/v1",
            "https://scalar-staging.vector.im/api",
            "https://scalar-staging.riot.im/scalar/api"
        ],
        "bug_report_endpoint_url": "https://element.io/bugreports/submit",
        "defaultCountryCode": "BE",
        "showLabsSettings": false,
        "features": { },
        "default_federate": true,
        "default_theme": "light",
        "roomDirectory": {
            "servers": [
                "matrix.org",
                "{{ .Values.homeserver_url }}"
            ]
        },
        "piwik": {
            "url": "/",
            "whitelistedHSUrls": [""],
            "whitelistedISUrls": ["", ""],
            "siteId": 0
        },
        "enable_presence_by_hs_url": {
            "https://{{ .Values.homeserver_url }}": true
        },
        "settingDefaults": {
            "breadcrumbs": true
        },
        "jitsi": {
            "preferredDomain": "jitsi.riot.im"
        }
    }
